version: '3'
services:
  rockpaperscissors-server:
    build:
      context: .
      dockerfile: Dockerfile-Server
    container_name: rockpaperscissors-server
    environment:
      "ConnectionStrings:DefaultConnection": "Server=tcp:wthrps-azuresql-server-505632015.database.windows.net,1433;Initial Catalog=RockPaperScissorsBoom;Persist Security Info=False;User ID=azureuser;Password=M1cr0s0ft2018@!;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
    ports:
        - "80:80"
